param(
    [string]$DropZone = "C:\GitHub\the-drop-zone",
    [string]$NeonMansion = "C:\GitHub\neon-mansion"
)

$ErrorActionPreference = "Stop"

$sourceRoot = Join-Path $DropZone "retro-game-assets\source-packs\kaykit"
$godotRoot = Join-Path $NeonMansion "godot"
$addonsRoot = Join-Path $godotRoot "addons"
$licenseRoot = Join-Path $godotRoot "third_party_licenses\kaykit"
$stagingRoot = Join-Path $godotRoot "assets\neon-mansion"

$packs = @(
    @{ Folder = "Dungeon-Remastered"; Addon = "kaykit_dungeon_remastered" },
    @{ Folder = "Furniture-Bits"; Addon = "kaykit_furniture_bits" },
    @{ Folder = "Restaurant-Bits"; Addon = "kaykit_restaurant_bits" },
    @{ Folder = "Prototype-Bits"; Addon = "kaykit_prototype_bits" }
)

Write-Host "Neon Mansion - KayKit Godot sync" -ForegroundColor Cyan
Write-Host "Source: $sourceRoot"
Write-Host "Target: $godotRoot"

if (-not (Test-Path $sourceRoot)) {
    throw "KayKit source folder not found. Initialise the Drop Zone submodules first: git submodule update --init --recursive"
}

New-Item -ItemType Directory -Force -Path $addonsRoot | Out-Null
New-Item -ItemType Directory -Force -Path $licenseRoot | Out-Null

# Project-facing organisation. These folders contain our Neon Mansion scenes/materials,
# not the untouched third-party source packs.
$folders = @(
    "architecture\walls",
    "architecture\doors",
    "architecture\stairs",
    "architecture\floors",
    "architecture\ceilings",
    "architecture\arches",
    "architecture\railings",
    "furniture\lounge",
    "furniture\bedrooms",
    "furniture\dining",
    "furniture\office",
    "kitchen",
    "games-arcade",
    "bathroom-pool",
    "props",
    "lighting",
    "nightmare-fx",
    "materials"
)
foreach ($folder in $folders) {
    New-Item -ItemType Directory -Force -Path (Join-Path $stagingRoot $folder) | Out-Null
}

foreach ($pack in $packs) {
    $packRoot = Join-Path $sourceRoot $pack.Folder
    if (-not (Test-Path $packRoot)) {
        throw "Missing source pack: $packRoot"
    }

    $sourceAddon = Join-Path $packRoot ("addons\" + $pack.Addon)
    $targetAddon = Join-Path $addonsRoot $pack.Addon

    if (-not (Test-Path $sourceAddon)) {
        throw "Godot addon folder not found in $($pack.Folder): $sourceAddon"
    }

    Write-Host "Syncing $($pack.Folder)..." -ForegroundColor Green
    if (Test-Path $targetAddon) {
        Remove-Item -Recurse -Force $targetAddon
    }
    Copy-Item -Recurse -Force $sourceAddon $targetAddon

    $license = Join-Path $packRoot "LICENSE.txt"
    if (Test-Path $license) {
        Copy-Item -Force $license (Join-Path $licenseRoot ($pack.Folder + "-LICENSE.txt"))
    }
}

$manifest = @"
# KayKit Sync Manifest

Generated by tools/sync-kaykit.ps1.

Source repository: doretradinguk-cyber/the-drop-zone
Source path: retro-game-assets/source-packs/kaykit

Imported Godot addons:
- KayKit Dungeon Remastered - structure, stairs, doors, modular architecture
- KayKit Furniture Bits - general room furniture
- KayKit Restaurant Bits - kitchen/dining/bar props
- KayKit Prototype Bits - blockout and temporary structural pieces

Do not edit files inside godot/addons/kaykit_* directly. Treat those folders as vendor source.
Create Neon Mansion-specific scenes, materials and variants under godot/assets/neon-mansion/.

Visual benchmark:
- dark teal / charcoal base surfaces
- near-black doors
- hot-magenta emissive trims
- acid-green / cyan indicators
- restrained low-poly/cel-shaded material treatment
- Nightmare Frequency corruption layered separately
"@
Set-Content -Encoding UTF8 -Path (Join-Path $licenseRoot "SYNC-MANIFEST.md") -Value $manifest

Write-Host ""
Write-Host "KayKit packs are organised for Godot." -ForegroundColor Cyan
Write-Host "Open Godot and allow it to import the new addon assets."
Write-Host "Vendor assets: godot/addons/kaykit_*"
Write-Host "Our working assets: godot/assets/neon-mansion/"
